# Generated by Django 4.0.3 on 2022-05-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('cure', models.TextField()),
            ],
        ),
    ]
