# Generated by Django 4.0.3 on 2022-05-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='cure',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
    ]
