# Generated by Django 4.0.3 on 2022-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_disease_cure_remove_disease_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='cure',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(default='ho'),
            preserve_default=False,
        ),
    ]
