# Generated by Django 4.0.3 on 2022-05-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_post_delete_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
